{"response_code":0,"results":
[{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"George Lucas directed the entire original Star Wars trilogy.",
    "correct_answer":"False",
    "incorrect_answers":["True"]},
{"category":"Entertainment: Film",
"type":"boolean","difficulty":"easy",
    "question":"&quot;Foodfight!&quot; earned less than $80,000 at box office.",
    "correct_answer":"True",
    "incorrect_answers":["False"]}]}